### ISSUE TITLE
RocksDBLog JMH benchmark should expose WriteOptions::setSync

### ISSUE THREAD

**Issue by franz1981** [belaban/jgroups-raft#117]
By default https://javadoc.io/static/org.rocksdb/rocksdbjni/6.8.1/org/rocksdb/WriteOptions.html#setSync(boolean) appear to be `false` meaning that the JMH benchmark re isn't fair with the other log implementations (that

In addition, I believe that this should be set to `true` on `RocksDBLog` unless users rely on raft replication to guarantee durability (bound to the number of replica(s)), but I see that's against the Raft protocol suggested by Ongaro (below more detail).
I've yet to investigate how file and LlevelDB logs still behave here.

According to the Ongaro Phd Thesis https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf I see that 

> 11.7.3 Avoiding persistent storage writes
>
> Many papers suggest using replication rather than stable storage for durability. 
>...
>The trade-off is that data loss is possible in catastrophic events.

meaning that properly durable (with power-failure guarantee) writes are mandatory.

**Comment by belaban** [comment]
Yes, we should enable this on RocksDB, too.

More important, though (IMO): we should measure perf of the various log impls and get rid of the ones that don't perform well. I mean, I don't see a reason to have both LevelDB and RocksDB, as they're very similar, anyway. Or use MapDB, which IIRC is unmaintained...

**Comment by belaban** [comment]
Also, I want to move most of the logic out of the log impls into RAFT; the logs should be simple enough to implement and only focus on fast reads and writes.

**Comment by belaban** [comment]
This issue is moot as I removed RocksDB, closing it.
