### ISSUE TITLE
LevelDB batch append is not using batching

### ISSUE THREAD

**Issue by franz1981** [belaban/jgroups-raft#121]
`LevelDBLog` is performing a `db.write` for each element in the batch instead just once per batch

see
![image](https://user-images.githubusercontent.com/13125299/161413681-37786b1d-cd3d-40fb-adde-fde7e60c0509.png)

**Comment by belaban** [comment]
Ouch! Good catch and simple fix...

**Comment by belaban** [comment]
The good thing is that we never send more than 1 LogEntry, but when batching is implemented, this would hurt us badly!

**Comment by belaban** [comment]
Moved batch close out of loop
