### ISSUE TITLE
Update demo to latest version, create image

### ISSUE THREAD

**Issue by belaban** [belaban/jgroups-raft#124]
Demo is at [1].

There should also be a reference to the demo in the manual.

[1] http://belaban.blogspot.com/2020/12/running-jgroups-raft-as-service.html

**Comment by jabolina** [comment]
Just checked the demo and everything is working. Also checked with JGroups 5.2.12.Final and JGroups-RAFT 1.0.10.Final.

**Comment by belaban** [comment]
Thanks
