### ISSUE TITLE
Log refactoring

### ISSUE THREAD

**Issue by belaban** [belaban/jgroups-raft#127]
Streamline the `Log` interface:
* `truncate()` should return `first_appended` (simplifies/eliminates code)
* Remove parameter `overwrite` in `append()` (always `true`)
* Log.append() should return `last_appened` to avoid `log.append(index, ...) -> last=log.lastAppened()` sequence (1 unneeded read)

**Comment by franz1981** [comment]
append entries should use a collection (ArrayList or Queue API) signature to replace the existing one based on the array or the caller (now single-thread) cannot decide to reuse the same collection over and over, causing an array allocation to happen on the hot-path, for each append entires call

**Comment by belaban** [comment]
* `truncate()` was let unchanged as `log.lastAppended()` always returns a cached variable, never reads from the filesystem (in all log impls)
