### ISSUE TITLE
Log: make syncing to disk configurable

### ISSUE THREAD

**Issue by belaban** [belaban/jgroups-raft#130]
Some log implementations (e.g. `LevelDBLog`) cache writes and then batch the writes to disk (fsync). To enable or disable this, `log_use_fsync` can be set to `true` (default: `false`). This ensures that an append to a log guarantees that the change was written to disk before returning. Caveat: this reduces performance, pending the implementation of request batching.

**Comment by franz1981** [comment]
The same thing could be done on the file log as well, so we can compare between the twos

**Comment by belaban** [comment]
You're just too fast, I sent you an email with this suggestion 30s ago! :-)
