### ISSUE TITLE
Expose sync and other properties of the file-based log

### ISSUE THREAD

**Issue by franz1981** [belaban/jgroups-raft#131]
This is a children of https://github.com/belaban/jgroups-raft/issues/130 but re the file based log.

There are few other properties that, in the current form, would be beneficial to expose to "us": I don't know if it makes sense to bring them at the user level in the XML or just use system properties that just developers will be aware of, @belaban suggestions?

**Comment by belaban** [comment]
Good morning @franz1981 !
In general, I don't like system props, as they apply to *all* apps running in the same JVM. I suggest expose all configuration that you think a user should be able to change, via `@Property` in (e.g.) `RAFT`.
Also, if you have metrics, e.g. hit/miss ratio, make it visible via `@ManagedAttribute`, too.

**Comment by franz1981** [comment]
@belaban 
As part of this I would like to get rid of volatile/synchronized in the file base log: is it safe?

**Comment by belaban** [comment]
Yes, it should be safe as the log is accessed by RAFT by a single thread.
