### ISSUE TITLE
Replace the concurrent skip list on LogCache with a ArrayRingBuffer 

### ISSUE THREAD

**Issue by franz1981** [belaban/jgroups-raft#132]
`ArrayRingBuffer` allows to use just a single (expandable) array to store log entry ranges:
- saving pointer chasing of a skip list (making clear/truncate much more efficient
- without concurrent behaviours (the log is accessed by the same thread)
- no need for boxing Integer keys
- `O(1)` lookup and `O(1)` append on steady state (with the max capacity is reached)

There are still both bug fixes and improvements on the ring buffer API to make it easier to use and less error prone.
To not mention that, given that it expose the allowed sequence ranges (in the form of tail/head long sequences), 
some attention is required on reload.
I'll soon open a PR to discuss about it and getting rid of the usage of the same on the file log.

**Comment by belaban** [comment]
Perhaps it would be a good idea to add a unit test for `ArrayRingBuffer`?

**Comment by franz1981** [comment]
@belaban Already on master

**Comment by belaban** [comment]
+1
