### ISSUE TITLE
RequestTable skip list can be replaced by ArrayRingBuffer

### ISSUE THREAD

**Issue by franz1981** [belaban/jgroups-raft#138]
RequestTable is popping up in many flamegraph profile data due to the heavyweight skip list map used to track requests: given that it seems to be updated on commit index, it seems a good fit for the array ring buffer data structure, that's a sliding window over `(commit index, last append]` entries, wdyt?

**Comment by belaban** [comment]
Is this low hanging fruit? I would assume that flamegraphs are dominated by fsync() (when enabled)... Other than that I don't mind replacing sorted hashmaps with your ringbuffer.

**Comment by franz1981** [comment]
> Is this low hanging fruit?

I suppose so, although if you try run async-profiler with `-e alloc` (or `-e alloc,cpu` while configuring a `profile.jfr` output) it pop-up easily. 

Same should be said about the `array` signature for append entries: it would be better to expose a collection/array list instead, to help the caller to save allocating it for each appending operation.
There are small things that just save tons of memory in the hot path

**Comment by belaban** [comment]
Can you add the last concern to https://github.com/belaban/jgroups-raft/issues/127?
