### ISSUE TITLE
InMemoryLog entries on repeated counter perf runs keep on growing

### ISSUE THREAD

**Issue by franz1981** [belaban/jgroups-raft#152]
While running single node repeated tests with `InMemoryLog` performance degrades over runs because LogEntry on `InMemoryLog::entries` keep on growing.

**Comment by belaban** [comment]
`InMemoryLog` is supposed to be used only by unit tests. However, we could replace `entries` with `ArrayRingBuffer` if you wanted

**Comment by franz1981** [comment]
I would rather disable to set it by user(s) if is not well-behaving - and just it to exist on test packages

People that doesn't want to fsync can just use the file log on tmpfs without fsync

**Comment by belaban** [comment]
ah, ok, good idea. I'll move it to the test package then!

**Comment by belaban** [comment]
This means #153 is moot then?

**Comment by belaban** [comment]
On second thought, InMemoryLog might be useful to test a setup that doesn't write to disk, ie. when testing RTTs. I'll leave InMemoryLog where it is and rather implement this issue and #153. Not very high prio, though...
