### ISSUE TITLE
Weird Thread::yield presence on single node benchmark

### ISSUE THREAD

**Issue by franz1981** [belaban/jgroups-raft#157]
I'm running a single node perf counter run using 8/12 threads of my CPU, file log and tmp without fsync.

![image](https://user-images.githubusercontent.com/13125299/166265250-1fd2c5b6-9433-4215-809d-2cb87a0acf69.png)

As shows, there's a huge amount of Thread::yield calls on `TransferQueueBundler::send`, is it normal @belaban?

**Comment by belaban** [comment]
Is this with JGroups 5.2.2? I don't see where `TQB.send()` calls `Thread.yield()`... This method only adds a message to an `ArrayBlockingQueue`...

**Comment by franz1981** [comment]
I've tried the latest master of jgroups-raft

**Comment by franz1981** [comment]
Cleaned m2 repo and now is disappeared: maybe I was using some custom version I did months ago :P

**Comment by belaban** [comment]
OK, good. I know that other bundlers (such as RingBufferBundler) have a yield (if configured accordingly), but TransferQueueBundler doesn't.
