### ISSUE TITLE
Merge SyncCounter/AsyncCounter and simplify CounterPerf

### ISSUE THREAD

**Issue by belaban** [belaban/jgroups-raft#164]
This is getting too complicated... Things to change:

* Merge Sync/AsyncCounter -> `Counter`, which has both sync and async methods, so we don't need to diff between `SyncCounter` and `AsyncCounter` (and their impls, too)
* Make only the `Updater` configurable in `CounterPerf`. An `Updater` gets a `Counter` and can then choose what to do (use sync or async)
* `CounterPerf` is configured with an `Updater` impl (the former becomes an interface)

**Comment by pruivo** [comment]
> * Merge Sync/AsyncCounter -> `Counter`, which has both sync and async methods, so we don't need to diff between `SyncCounter` and `AsyncCounter` (and their impls, too)

Note that `SyncCounter` and `AsyncCounter` have methods to convert between interfaces. About the "implementations", there is only a single implementation.

> * Make only the `Updater` configurable in `CounterPerf`. An `Updater` gets a `Counter` and can then choose what to do (use sync or async)

What is the difference between the "new" `Updater` and the current interface https://github.com/belaban/jgroups-raft/blob/a9f99f07173b0ad7658e7bd06eb692147c317e73/src/org/jgroups/perf/CounterBenchmark.java ?

**Comment by belaban** [comment]
I created common base interface `Counter`, with methods `getName()` and `sync()` and `async()`. Both `SyncCounter` and `AsyncCounter` extend it.

**Comment by belaban** [comment]
I haven't tackled that one yet, but the idea is that `Updater` is given a `Counter` (and, of course, a `LongSupplier`) and needs to implement only a single method `update()`.

**Comment by pruivo** [comment]
> I haven't tackled that one yet, but the idea is that `Updater` is given a `Counter` (and, of course, a `LongSupplier`) and needs to implement only a single method `update()`.

It is a bit restrictive IMO. If you want a node to generate `N` requests concurrently, you need 1 thread per `Updater` with `SyncCounter`, but not for the `AsyncCounter`.
Well, you don't even need to create any thread at all for `AsyncCounter`.

Francesco wants to implement a fixed rate perf-test and a single `Updater` interface makes it more complicated (since it would have to change code in ` CounterTest` to implement the new logic)

**Comment by belaban** [comment]
Good point! I'll think about this...
