### ISSUE TITLE
RAFT: setAsync() with IGNORE_RESULT

### ISSUE THREAD

**Issue by belaban** [belaban/jgroups-raft#169]
Currently, flamegraphs on the leader show that `CompletableFuture.complete()` uses quite some CPU time. When a response is received, the following happens:
* The commit-table is updated
* The log-index is advanced and the entries between the old and new commit-index are applied to the state machine
* All elements in the request table in range [old-commit-index .. commit-index] are notified of the result and removed

This is a considerable cost. If we're not interested in the result, an option `IGNORE_RESULT` could be introduced to `setAsync()`. The semantics are fire-and-forget, so the caller doesn't know whether/when the request got a majority, and whether it was applied to the log. The following things would still be done when receiving a result:
* The entry in the request-table should be acked, to see if a majority was reached, and the commit-index moved and the state machine updated accordingly
* However, `complete()` would not have to be called on the entry in the request-table, eliminating that cost
* `REDIRECT` would not have to wait for results

Investigate if this is useful

**Comment by pruivo** [comment]
In the current code, the `REDIRECT` response isn't needed. The leader sends a `REDIRECT` response for each index committed but later sends a new `AppendRequest` with the latest `commit-index`; when the follower applies the index to the `state-machine`, you can use the `apply()` method return value as a response.

I would go a step further and merge the `REDIRECT` into `RAFT`. The only job that `REDIRECT` does is `if not leader; then forward to leader; else use RAFT `

**Comment by belaban** [comment]
@pruivo Remember: one concern / one class? :-) `REDIRECT` is needed to forward requests/responses between followers and leader!

**Comment by belaban** [comment]
You mean not send the data, only the ID? That would certainly work, care to create an issue?

**Comment by belaban** [comment]
Actually, let's do this in *this* ticket directly...

**Comment by belaban** [comment]
Hmm... is there a real-world scenario for this? `Counter.set()` comes to mind (all other methods have a return value), but I can't think of a use case where this is useful. Stress tests?

**Comment by belaban** [comment]
A test really stressing the system would be
```java
index=1;
while(!stop) {
     counter.set(i++, Options.IGNORE_RETURNVALUE);
}
```

**Comment by belaban** [comment]
My gut feeling is that the above use case is not needed, for now at least with counters: what's the rationale for setting a value numerous times, rather than once? A stock feed? Hmm, IMO that use case doesn't warrant Raft...

The better use case for `IGNORE_RETURN_VALUE` is to reduce the amount of marshalling (as @pruivo mentioned above): `REDIRECT` does not have to serialize/deserialize responses from leaders to followers. This might yield a slight increase in performance

**Comment by belaban** [comment]
I'll experiment with this, starting today..

**Comment by pruivo** [comment]
My suggestion is to piggy-back into `AppendEntriesRequest` a mapping between `REDIRECT` ids => Log `index+term`. When the follower applies `index+term` log entry, it has the response from the `StateMachine#apply()` and can complete the `REDIRECT` request.
It reduces the number of messages generated at a cost of increased latency.

**Comment by belaban** [comment]
I'll think about this. However, 2 downsides:
* Tight coupling between `RAFT` and `REDIRECT`, violating separation of concerns
* The last request in a batch is always delayed by 1 sec (`resend_interval`). If we send 5 requests, with a wait time of a few ms between, we'd have to wait `5 x 1s` total...

**Comment by belaban** [comment]
Hmm... we would have to change every method in consumer interfaces/classes of `setAsync()`, e.g. `SyncCounter`, `AsyncCounter` etc.
Perhaps we should restrict this to `REDIRECT` only? But then, the attribute applies to _all_ requests...

**Comment by pruivo** [comment]
Second though, I would probably drop this change if it becomes so "complex" and confusing.
IMO, a counter with `IGNORE_RETURN_VALUES` does not make much sense... what are the semantics of `counter.get()` with that option enabled? `compareAndSet`?
What are the benefits of `IGNORE_RETURN_VALUES`? `REDIRECT` still needs some kind of `ack` when the operation completes otherwise how do you know what happens to your request?.
`StateMachine#apply()` still marshalls the response into a byte array.

**Comment by belaban** [comment]
Further changes:
* `apply()` on the follower does not need to return a response. Adding parameter `require-rsp`

**Comment by belaban** [comment]
A quick perftest with `CounterPerf` shows a 20% improvement (`16546` -> `19979`) for `SyncBenchmark` and 6% for `AsyncBenchmark` (`19781` -> `21017`)
