### ISSUE TITLE
InternalCommand with FileBasedLog problem

### ISSUE THREAD

**Issue by jabolina** [belaban/jgroups-raft#188]
I was trying to set a test for #176 but found a problem with the serialization of internal commands with the file-based log. When the entry is serialized and written to the log, it ignores the `internal` flag, leading to a corruption of the state machine. A node that recovers from the log parses the command without the flag, applying the command to the actual state machine, for example, increasing the counter with whatever value the command has. 

Here is a diff with a small reproducer: https://github.com/jabolina/jgroups-raft/compare/master...internal-cmd-serde

The fix seems simple enough to get in place. The problem, for me, is how can we be backward compatible in this case?

**Comment by pruivo** [comment]
just do the fix. The file-based log is young and it isn't the default; it is unlikely that it is used in production.

**Comment by belaban** [comment]
Is this related to [1]?
[1] https://github.com/belaban/jgroups-raft/issues/189

**Comment by belaban** [comment]
Yes, I'd just apply that change. I do think though that FileBasedLog is the future, _not_ LevelDB...

**Comment by jabolina** [comment]
> Is this related to [1]? [1] #189

I think so, without this, #189 will not work properly with the FileBasedLog.

I'll open a PR for this, so it unlocks further progress for dyn membership.
