### ISSUE TITLE
Remove AsyncCounter and SyncCounter interfaces

### ISSUE THREAD

**Issue by pruivo** [belaban/jgroups-raft#191]
Package https://github.com/belaban/jgroups-raft/blob/8e1b052ba7e610fee2c4169bb85a5691cdede97c/src/org/jgroups/blocks/atomic/package-info.java is temporary and should be removed when merged in JGroups

**Comment by belaban** [comment]
OK, I'll apply this PR when JGroups 5.2.10.Final has been released
