### ISSUE TITLE
ELECTION: start / stop elections based on view changes

### ISSUE THREAD

**Issue by belaban** [belaban/jgroups-raft#20]
Raft [1] duplicates some of the JGroups functionality: the goal of this issue is to remove that duplication and use JGroups wherever possible, e.g. for heartbeats and election kickoffs.
Also, cluster membership changes as described in ch. 4 of [1] should be simple to implement with this change.
Examples:
- When a view size drops under `majority`, the leader steps down
- When a view size reaches `majority` members, start the election process. When a leader has been chosen, stop the election timer
- When a leader is not in the next view, start an election

Advantages:
- No constant heartbeating, this is done by JGroups anyway
- Easy addition of members which would change `majority`
- No need to mark views as _special entries_ in the log

Details are in [2].

[1] https://github.com/ongardie/dissertation
[2] https://github.com/belaban/jgroups-raft/blob/master/doc/design/Election.txt

**Comment by ongardie** [comment]
> No need to mark views as special entries in the log

Can you explain? I think you still need this for dynamic membership changes. Or does JGroups provide some persistent storage that makes it unnecessary?

> https://github.com/belaban/jgroups-raft/blob/master/doc/design/Election.txt

That link's broken.

**Comment by belaban** [comment]
Give me a few days to complete the design document (it's on a separate branch), and I'd be happy to get your feedback

**Comment by ongardie** [comment]
@belaban sounds good, looking forward to seeing it.

**Comment by belaban** [comment]
Need to rethink this; as https://github.com/belaban/jgroups-raft/issues/21 changed things slightly.

**Comment by bwzhang2011** [comment]
@belaban, any update with such issue ? we're looking forward to some raft implementation, hope 0.4 released not long in the future with those issues fixed and completed.

**Comment by belaban** [comment]
Sorry, but jgroups-raft has been dormant for a while now, and I don't expect to be able to spend much time on it in the near future.

**Comment by belaban** [comment]
Hi @valdar  Andrea: nope

**Comment by belaban** [comment]
OK, I finally changed this to take advantage of JGroups views:
* An election is started only on a view change, by the coordinator
* When the majority is reached, the coord solicits votes from all members
* The member with the highest term (longest log) wins and becomes leader
* If all logs are equal, then the leader is the oldest member (the coord)
* Details are in [1]

This has a few advantages:
* No election / heartbeat timers -> no concurrent elections and no constant traffic to prevent followers from becoming candidates
* As a matter of fact, Candidate has been removed: we only have Leaders and Followers

The outcome should be the same as the original Raft election algorithm.

[1] https://github.com/belaban/jgroups-raft/blob/master/doc/design/Election.txt
