### ISSUE TITLE
this.raftHandle.channel().disconnect() and reconnect  trigger error "not found in retransmission table"

### ISSUE THREAD

**Issue by jackjoesh** [belaban/jgroups-raft#213]
hi this my previous issue:
https://github.com/belaban/jgroups-raft/issues/212 （can't remove leader by method of RaftHandle's removeServer）

I have tried this way to trigger revote in clusters:
        this.raftHandle.channel().disconnect();
        Thread.sleep(1000l);
        this.raftHandle.raft().log(null); // <--- new line
        this.raftHandle.channel().connect(this.raftClusterName);

But there still has a problem:
If there have three nodes (A, B, C)in this clusters,  the time line of event is like this:
1. C  becomes leader
2   C triggers revoting by disconnecting and reconnecting
3  A   becomes leader
4  A triggers revoting by disconnecting and reconnecting
5. finally, C raises error:    [org.jgroups.protocols.pbcast.NAKACK2] - JGRP000041: 192.168.10.170[7803]: message 192.168.10.170[7803]::1 not found in retransmission table

And when occurring  this error,  the whole cluster doesn't elect any leader later.

How can I solve this problem? thanks

**Comment by jackjoesh** [comment]
> Sorry for the delay, @jackjoesh. I'll need to take a closer look at this. Once I have something, I reach back.

thank you , look forward to your investigating result

**Comment by belaban** [comment]
Jose found a bug: https://issues.redhat.com/browse/JGRP-2720
Will be fixed in 5.2.17, to be released within the week

**Comment by jackjoesh** [comment]
> Jose found a bug: https://issues.redhat.com/browse/JGRP-2720 Will be fixed in 5.2.17, to be released within the week

great, look forward to this new version, I will test it

**Comment by jabolina** [comment]
@jackjoesh JGroups 5.2.17.Final is released.

**Comment by jackjoesh** [comment]
> @jackjoesh JGroups 5.2.17.Final is released.

thanks, I have tested pass

**Comment by jabolina** [comment]
Thanks, @jackjoesh!
