### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by hrstoyanov** [belaban/jgroups-raft#215]
Hi all, I have a few questions:

1. Can you, please enable GitHub discussions for this project - I joined the Google group, but cannot post questions there.

2. Is this project active? I see no release for 2023, and raft is hard enough to get right without frequent bug-fix releases. Is anyone using jgroups-raft for serious projects?

3. Can you compare jgroups-raft to Aeron:

https://github.com/real-logic/aeron

**Comment by belaban** [comment]
1. I see you joined the google group; you should be able to post (use the email you registered under). I'll enable discussions anyway
2. The last release was in May of this year: https://central.sonatype.com/artifact/org.jgroups/jgroups-raft/1.0.11.Final/versions
3. I'm afraid I have no time.

**Comment by hrstoyanov** [comment]
Thanks Bela

**Comment by hrstoyanov** [comment]
Thanks. Please close this issue.
