### ISSUE TITLE
All members changeRole for Candidate, How to solve it ?

### ISSUE THREAD

**Issue by juaby** [belaban/jgroups-raft#36]
```java
   protected boolean voteFor(final Address addr) {
        if(addr == null) {
            voted_for=null;
            return true;
        }
        if(voted_for == null) {
            voted_for=addr;
            return true;
        }
        return voted_for.equals(addr); // a vote for the same candidate in the same term is ok
    }

protected void handleVoteRequest(Address sender, int term, int last_log_term, int last_log_index) {
        if(local_addr != null && local_addr.equals(sender))
            return;
        if(log.isTraceEnabled())
            log.trace("%s: received VoteRequest from %s: term=%d, my term=%d, last_log_term=%d, last_log_index=%d",
                      local_addr, sender, term, raft.currentTerm(), last_log_term, last_log_index);
        boolean send_vote_rsp=false;
        synchronized(this) {
            if(voteFor(sender)) {
                if(sameOrNewer(last_log_term, last_log_index))
                    send_vote_rsp=true;
                else {
                    log.trace("%s: dropped VoteRequest from %s as my log is more up-to-date", local_addr, sender);
                }
            }
            else
                log.trace("%s: already voted for %s in term %d; skipping vote", local_addr, sender, term);
        }
        if(send_vote_rsp)
            sendVoteResponse(sender, term); // raft.current_term);
    }
```

here!!!!!
return voted_for.equals(addr); // a vote for the same candidate in the same term is ok

**Comment by belaban** [comment]
Can you describe what the problem is ?

**Comment by juaby** [comment]
Is it possible to become a candidate for all members?
This happens, how election？

**Comment by belaban** [comment]
Yes, everyone can become a candidate. Check the Raft paper for details.

**Comment by juaby** [comment]
I have 3 nodes，after started serve， erveryone become a candidate......

**Comment by juaby** [comment]
![a](https://cloud.githubusercontent.com/assets/4152978/8495075/3ec63a66-219d-11e5-9d41-a0f6b711e511.png)
![b](https://cloud.githubusercontent.com/assets/4152978/8495074/3ec3f7d8-219d-11e5-92dc-52a6a3be8316.png)
![c](https://cloud.githubusercontent.com/assets/4152978/8495076/3eec020a-219d-11e5-9dfb-291b70b77c48.png)

**Comment by belaban** [comment]
Check if the JGroups member form a cluster; cause if they don't detect each other, every member thinks it's in its own cluster. I suggest use Draw with the same XML config and see if they form a cluster.

**Comment by juaby** [comment]
2.8. It doesn’t work !
Note	The section below refers to JGroups versions prior to 3.5. In 3.5 and later versions, mcast (see below) should be used.
Make sure your machine is set up correctly for IP multicasting. There are 2 test programs that can be used to detect this: McastReceiverTest and McastSenderTest. Start McastReceiverTest, e.g.

java org.jgroups.tests.McastReceiverTest
Then start McastSenderTest:

java org.jgroups.tests.McastSenderTest

It work !

**Comment by juaby** [comment]
hi lelaban,

Make sure your machine is set up correctly for IP multicasting. There are 2 test programs that can be used to detect this: McastReceiverTest and McastSenderTest. Start McastReceiverTest, e.g.

java org.jgroups.tests.McastReceiverTest
Then start McastSenderTest:

java org.jgroups.tests.McastSenderTest

It work !

![r](https://cloud.githubusercontent.com/assets/4152978/8517158/0c9daf88-23f0-11e5-8625-c8be6ff5196c.png)

your suggest:
Check if the JGroups member form a cluster; cause if they don't detect each other, every member thinks it's in its own cluster. I suggest use Draw with the same XML config and see if they form a cluster.

My linux server NO X-WINDOWS

how ? and sugguest ? 

thanks!

**Comment by juaby** [comment]
Check if the JGroups member form a cluster; cause if they don't detect each other, every member thinks it's in its own cluster. I suggest use Draw with the same XML config and see if they form a cluster.

If the operating system is not configured DNS, this problem occurs？

**Comment by belaban** [comment]
So I assume your problem is still persisting ? Check the usual suspects in JGroups [1]. Also check with Draw in JGroups; this isn't a jgroups-raft problem.

[1] https://github.com/belaban/workshop/blob/master/slides/admin.adoc#problem-13-aws
