### ISSUE TITLE
Reset heartbeat timer on vote

### ISSUE THREAD

**Issue by kuujo** [belaban/jgroups-raft#45]
I may be missing something, so apologies if I'm reading your code wrong :-) 
It appears that when handling a `VoteRequest`, the heartbeat timer is never reset upon voting for a candidate.
https://github.com/belaban/jgroups-raft/blob/master/src/org/jgroups/protocols/raft/ELECTION.java#L191-L211
Raft specifies that a follower resets its election timeout when it grants a vote to a candidate. This ensures that a follower doesn't vote for a candidate and then immediately timeout, transition to candidate itself, increment its term, vote for itself, and ultimately force a newly elected leader to step down.

**Comment by belaban** [comment]
Hi Jordan,
sorry for the delay, just returned from NYC and will be away for the better part of the next 2 weeks, too.
I'll get to this *eventually* (no pun intended :-))

**Comment by kuujo** [comment]
:-P no rush was just poking around and noticed it. Thought I'd point it out in case I was reading it right.

**Comment by pandaworrior** [comment]
Hi Jordan,

There are two timers, heartbeat timer and election timer. As you mentioned,
the election timer must be reset when every time the election starts, in
order to avoid split vote. But, there is no need to reset the heartbeat
timer.

Thanks,
   Cheng


On Fri, Mar 25, 2016 at 2:52 PM, Jordan Halterman <notifications@github.com>
wrote:

> I may be missing something, so apologies if I'm reading your code wrong
> :-)
> It appears that when handling a VoteRequest, the heartbeat timer is never
> reset upon voting for a candidate.
>
> https://github.com/belaban/jgroups-raft/blob/master/src/org/jgroups/protocols/raft/ELECTION.java#L191-L211
> Raft specifies that a follower resets its election timeout when it grants
> a vote to a candidate. This ensures that a follower doesn't vote for a
> candidate and then immediately timeout, transition to candidate itself,
> increment its term, vote for itself, and ultimately force a newly elected
> leader to step down.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/belaban/jgroups-raft/issues/45>
>



-- 
Best wishes!

                 Sincerely,

ChengLi,
Ph.D Candidate Student,
Max Planck Institute for Software System,
Campus E 1 4,
D-66123 Saarbruecken,
Germany

**Comment by belaban** [comment]
In [1], I completely redesigned the way elections work; an election is now triggered and controlled by the JGroups coordinator. This means that election and heartbeat timers are gone; the coord solicits votes from everyone when an election is required and elects a leader based on majority/last-term/longest-index (if all are equal, then rank-based).

While this eliminates concurrent elections, the election outcome should still be correct.

[1] https://github.com/belaban/jgroups-raft/issues/20
[1] https://github.com/belaban/jgroups-raft/blob/master/doc/design/Election.txt

**Comment by belaban** [comment]
@kuujo @pandaworrior If you have time to look at the code, let me know if you spot something that violates Raft: more than one leader or leader not being the one with the highest term/longest log.
