### ISSUE TITLE
nexus issue while building from scratch

### ISSUE THREAD

**Issue by vipulg** [belaban/jgroups-raft#46]
ivy:retrieve]  nexus-snapshots: unable to get resource for org/apache/logging/log4j#log4j;2.6.2: res=${nexus.snapshots.url}/org/apache/logging/log4j/log4j/2.6.2/log4j-2.6.2.pom: java.net.MalformedURLException: no protocol: $
nexus.snapshots.url}/org/apache/logging/log4j/log4j/2.6.2/log4j-2.6.2.pom
ivy:retrieve]          :: org.mapdb#mapdb;1.0.8: several problems occurred while resolving dependency: org.mapdb#mapdb;1.0.8 {_=[_]}:
ivy:retrieve]  several problems occurred while resolving dependency: org.sonatype.oss#oss-parent;7 {}:
ivy:retrieve]  nexus-snapshots: unable to get resource for org/sonatype/oss#oss-parent;7: res=${nexus.snapshots.url}/org/sonatype/oss/oss-parent/7/oss-parent-7.jar: java.net.MalformedURLException: no protocol: ${nexus.snapsh
ts.url}/org/sonatype/oss/oss-parent/7/oss-parent-7.jar
ivy:retrieve]  nexus-snapshots: unable to get resource for org/sonatype/oss#oss-parent;7: res=${nexus.snapshots.url}/org/sonatype/oss/oss-parent/7/oss-parent-7.pom: java.net.MalformedURLException: no protocol: ${nexus.snapsh
ts.url}/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
ivy:retrieve]  nexus-snapshots: unable to get resource for org/mapdb#mapdb;1.0.8: res=${nexus.snapshots.url}/org/mapdb/mapdb/1.0.8/mapdb-1.0.8.pom: java.net.MalformedURLException: no protocol: ${nexus.snapshots.url}/org/mapd
/mapdb/1.0.8/mapdb-1.0.8.pom
ivy:retrieve]          :: org.fusesource.leveldbjni#leveldbjni-all;1.8: several problems occurred while resolving dependency: org.fusesource.leveldbjni#leveldbjni-all;1.8 {_=[_]}:
ivy:retrieve]  several problems occurred while resolving dependency: org.fusesource.leveldbjni#leveldbjni-project;1.8 {}:
ivy:retrieve]  several problems occurred while resolving dependency: org.fusesource#fusesource-pom;1.9 {}:
ivy:retrieve]  nexus-snapshots: unable to get resource for org/fusesource#fusesource-pom;1.9: res=${nexus.snapshots.url}/org/fusesource/fusesource-pom/1.9/fusesource-pom-1.9.jar: java.net.MalformedURLException: no protocol:
{nexus.snapshots.url}/org/fusesource/fusesource-pom/1.9/fusesource-pom-1.9.jar
ivy:retrieve]  nexus-snapshots: unable to get resource for org/fusesource#fusesource-pom;1.9: res=${nexus.snapshots.url}/org/fusesource/fusesource-pom/1.9/fusesource-pom-1.9.pom: java.net.MalformedURLException: no protocol:
{nexus.snapshots.url}/org/fusesource/fusesource-pom/1.9/fusesource-pom-1.9.pom
ivy:retrieve]  nexus-snapshots: unable to get resource for org/fusesource/leveldbjni#leveldbjni-project;1.8: res=${nexus.snapshots.url}/org/fusesource/leveldbjni/leveldbjni-project/1.8/leveldbjni-project-1.8.pom: java.net.Ma
formedURLException: no protocol: ${nexus.snapshots.url}/org/fusesource/leveldbjni/leveldbjni-project/1.8/leveldbjni-project-1.8.pom
ivy:retrieve]  nexus-snapshots: unable to get resource for org/fusesource/leveldbjni#leveldbjni-all;1.8: res=${nexus.snapshots.url}/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.pom: java.net.MalformedURLEx
eption: no protocol: ${nexus.snapshots.url}/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.pom
ivy:retrieve]          :: org.testng#testng;6.8.+: several problems occurred while resolving dependency: org.sonatype.oss#oss-parent;3 {}:
ivy:retrieve]  nexus-snapshots: unable to get resource for org/sonatype/oss#oss-parent;3: res=${nexus.snapshots.url}/org/sonatype/oss/oss-parent/3/oss-parent-3.jar: java.net.MalformedURLException: no protocol: ${nexus.snapsh
ts.url}/org/sonatype/oss/oss-parent/3/oss-parent-3.jar
ivy:retrieve]  nexus-snapshots: unable to get resource for org/sonatype/oss#oss-parent;3: res=${nexus.snapshots.url}/org/sonatype/oss/oss-parent/3/oss-parent-3.pom: java.net.MalformedURLException: no protocol: ${nexus.snapsh
ts.url}/org/sonatype/oss/oss-parent/3/oss-parent-3.pom
ivy:retrieve]          :: com.beust#jcommander;1.+: several problems occurred while resolving dependency: org.sonatype.oss#oss-parent;3 {}:
ivy:retrieve]  nexus-snapshots: unable to get resource for org/sonatype/oss#oss-parent;3: res=${nexus.snapshots.url}/org/sonatype/oss/oss-parent/3/oss-parent-3.jar: java.net.MalformedURLException: no protocol: ${nexus.snapsh
ts.url}/org/sonatype/oss/oss-parent/3/oss-parent-3.jar
ivy:retrieve]  nexus-snapshots: unable to get resource for org/sonatype/oss#oss-parent;3: res=${nexus.snapshots.url}/org/sonatype/oss/oss-parent/3/oss-parent-3.pom: java.net.MalformedURLException: no protocol: ${nexus.snapsh
ts.url}/org/sonatype/oss/oss-parent/3/oss-parent-3.pom
ivy:retrieve]          :: commons-io#commons-io;2.4: several problems occurred while resolving dependency: commons-io#commons-io;2.4 {_=[_]}:
ivy:retrieve]  several problems occurred while resolving dependency: org.apache.commons#commons-parent;25 {}:
ivy:retrieve]  several problems occurred while resolving dependency: org.apache#apache;9 {}:
ivy:retrieve]  nexus-snapshots: unable to get resource for org/apache#apache;9: res=${nexus.snapshots.url}/org/apache/apache/9/apache-9.jar: java.net.MalformedURLException: no protocol: ${nexus.snapshots.url}/org/apache/apac
e/9/apache-9.jar
ivy:retrieve]  nexus-snapshots: unable to get resource for org/apache#apache;9: res=${nexus.snapshots.url}/org/apache/apache/9/apache-9.pom: java.net.MalformedURLException: no protocol: ${nexus.snapshots.url}/org/apache/apac
e/9/apache-9.pom
ivy:retrieve]  nexus-snapshots: unable to get resource for org/apache/commons#commons-parent;25: res=${nexus.snapshots.url}/org/apache/commons/commons-parent/25/commons-parent-25.pom: java.net.MalformedURLException: no proto
ol: ${nexus.snapshots.url}/org/apache/commons/commons-parent/25/commons-parent-25.pom
ivy:retrieve]  nexus-snapshots: unable to get resource for commons-io#commons-io;2.4: res=${nexus.snapshots.url}/commons-io/commons-io/2.4/commons-io-2.4.pom: java.net.MalformedURLException: no protocol: ${nexus.snapshots.ur
}/commons-io/commons-io/2.4/commons-io-2.4.pom
ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
ivy:retrieve]

**Comment by belaban** [comment]
This has been fixed a qhile ago (changed http -> https), but I forgot to close the case. Sorry!
