### ISSUE TITLE
Jgroups version incompatibility

### ISSUE THREAD

**Issue by mogarg** [belaban/jgroups-raft#50]
The jgroups version in the current pom.xml states the version **3.6.0.Final** however it does not recognize 
`org.jgroups.util.Util.waitUntilAllChannelsHaveSameView` which is used in the current project. It is only supported in version **4.0.0.Beta3** however that is not compatible with other symbols used from jgroups.

**Comment by belaban** [comment]
The thing is that I never use maven to build but Ivy which uses the latest 3.6.x where x=12. I'll change this in pom.xml.

**Comment by belaban** [comment]
Changed to `<version>3.6.12.Final</version>`. Although it would be better to say JGroups 3.6.x, but `<version>[3.6.,)</version>` didn't work...
