### ISSUE TITLE
Cannot apply entries in single node cluster

### ISSUE THREAD

**Issue by npepinpe** [belaban/jgroups-raft#69]
Related to #68 - when developing locally, it's common to test with a single node cluster. It seems the commit index is never incremented; perhaps I mis-configured something? Looking through the code, though, it seems like it's behaving as expected: we increment the commit index only when receiving append entries request, which the leader obviously doesn't send to itself. I think this could be solved by using the leader's own index to calculate the quorum.

Did I miss something or is this the intended behaviour?

EDIT: as a side note, using the leader's own match index when computing quorum has a nice side effect of allowing the append to the local log to be asynchronous, i.e. we can start replicating before the entry has been appended to the local log (this is described in section **10.2.1** in the original [thesis](https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf))

**Comment by belaban** [comment]
Closing this as PR #71 fixed this issue
