### ISSUE TITLE
ELECTION does not work with RAFT subclass

### ISSUE THREAD

**Issue by hypnoce** [belaban/jgroups-raft#72]
ELECTION protocol searches exactly for RAFT class : https://github.com/belaban/jgroups-raft/blob/bf5bca0440a68581bb91c6355545fc0dd17a1d13/src/org/jgroups/protocols/raft/ELECTION.java#L354 unlike the findProtocol more general method : https://github.com/belaban/JGroups/blob/1763ee1e06d2f71ee6ebdc8ab646ea4cc3b0b7f1/src/org/jgroups/stack/ProtocolStack.java#L751
Make sure ELECTION can find subclasses of RAFT.

**Comment by hypnoce** [comment]
@belaban thanks for merging. Will you be able to release this change or maybe you're waiting for other things to be merged/tested ?

**Comment by belaban** [comment]
Yes, I just released 0.5.1.Final
