### ISSUE TITLE
Demo ?

### ISSUE THREAD

**Issue by buko** [belaban/jgroups-raft#77]
Would love to  see a demo application of this: perhaps something runnable besides from the test that we could launch from the command line. Perhaps something like the jgroups Draw demo (http://www.jgroups.org/demos.html) could be adapted to jgroups-raft? This would also provide a nice starting point for exploration.

Is there any way to introspect a jgroups-raft cluster? I mean connect to it and determine who is the leader so that requests can be targeted to the leader? It seems RaftHandle does this but again it'd be nice to see exactly how it's to  be used.

**Comment by belaban** [comment]
What's the point of a Draw demo? It doesn't show the benefits of a consensus-based system IMO...
You can use probe.sh to introspect a jgroups-raft cluster, same as with regular JGroups except there are a bunch of additional protocols.
