### ISSUE TITLE
Message lost

### ISSUE THREAD

**Issue by hypnoce** [belaban/jgroups-raft#84]
In a single member use case, messages can be lost by potential overwriting previous indexes.
Use case : 
https://github.com/hypnoce/jgroups-raft/commit/ddbb0bd5aaf312d6da0f674bce6fb95c6daca8f3

In case of a single member (single member is the leader), the commit table is only updated by the resend thread looping back on the leader.
The append entry request is handled in a separate thread (either the resend thread or the loopback thread in a lower protocol extending TP with loopback_separate_thread=true). Each non-committed message will be re-appended and update the last_appended property : https://github.com/belaban/jgroups-raft/blob/858b66cc0eac2a1f541dfc981022b9d7900afee5/src/org/jgroups/protocols/raft/RAFT.java#L792

While the leader is busy committing itself, a new message can be written https://github.com/belaban/jgroups-raft/blob/858b66cc0eac2a1f541dfc981022b9d7900afee5/src/org/jgroups/protocols/raft/RAFT.java#L566 and `curr_index` can become lower than the real last appended.
Therefore a new message is written in an old index and also the returned completablefuture is never completed.

There are many ways to fix this, let me know what you think.

Thanks

**Comment by belaban** [comment]
I'm looking at your test now, will fix this by WED. What's your scenario, running Raft with one node only?

**Comment by hypnoce** [comment]
Yes the current scenario is a single raft node only. Thanks

**Comment by belaban** [comment]
I guess so, but I'm wondering what you do with a single node. IMO, the usefulness of Raft lies in consensus, and it is thus only useful with 3+ nodes...

**Comment by hypnoce** [comment]
That's true. In our case it's mainly use in functional test and dev env.
In a previous issue (see https://github.com/belaban/jgroups-raft/issues/68) I proposed to have a separate protocol to handle special single member case for RAFT instead of leaking the support into the RAFT protocol itself. WDYT ?

**Comment by belaban** [comment]
OK, I see. I still think a separate protocol is not warranted. This can and should be handled by RAFT itself.

**Comment by belaban** [comment]
OK, I guess my solution is to ignore entries in {{append()}} whose index < last_appended (in a synchronized(this))... Need to verify this. I also want to turn your unit test into a test which verifies that everyone appended the same content

**Comment by belaban** [comment]
I also modified TimeoutTest a bit and also test 3 nodes.
@hypnoce Can you test with this version and let me know if this works?
Cheers,

**Comment by belaban** [comment]
I just released 1.0.3
