### ISSUE TITLE
Create branch 0.5.x compatible with JGroups 4

### ISSUE THREAD

**Issue by pruivo** [belaban/jgroups-raft#93]
The last commit compatible with JGroups 4 is https://github.com/belaban/jgroups-raft/commit/6a60aa7e6c6060784709211cc267555fab8eff25

It would be nice to have a new branch from the commit above for future improvements/fixes.

**Comment by belaban** [comment]
I'll do this right away, gimme 1 hr

**Comment by belaban** [comment]
Created branch 4.x
